/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx_reg.h"

static void delay_ms(uint32_t ms)
{
    volatile uint32_t count;

    while (ms--)
    {
        count = 16000;

        while (count--)
        {
            __asm volatile ("nop");
        }
    }
}

int main(void)
{
	uint8_t led_state = 0;

	/* Enabling the clock for GPIOA & GPIOD Peripherals */
	RCC_AHB1ENR |= (1U << 0);
	RCC_AHB1ENR |= (1U << 3);

	/* Configure PD13 as general purpose output */
	GPIOD_MODER &= ~(3U << 26);
	GPIOD_MODER |= (1U << 26);

	/* Configure PA0 as general purpose input */
	GPIOA_MODER &= ~(3U << 0);

	/* Configure PD13 as push-pull */
	GPIOD_OTYPR &= ~(1U << 13);

	/* Configure PD13 as low speed */
	GPIOD_OSPEEDR &= ~(3U << 26);

	/* Configure PD13 as no pull up/down */
	GPIOD_PUPDR &= ~(3U << 26);

    /* start with LED OFF */
	GPIOD_BSSR |= (1U << 29);

	while(1)
	{
		if (GPIOA_IDR & (1U << 0))
		{
			delay_ms(20);

			if (GPIOA_IDR & (1U << 0))
			{
				/* Toggle LED state */
				led_state ^= 1U;

				if (led_state)
				{
					/* LED ON */
					GPIOD_BSSR |= (1U << 13);
				}
				else
				{
					/* LED OFF */
					GPIOD_BSSR |= (1U << 29);
				}

				/* Wait for button release */
				while(GPIOA_IDR & (1U << 0))
				{
				   /* wait */
				}

			}
		}
	}
}
