/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx_reg.h"

static void delay_ms(uint32_t ms)
{
    volatile uint32_t count;

    while (ms--)
    {
        count = 16000;

        while (count--)
        {
            __asm volatile ("nop");
        }
    }
}

int main(void)
{

	/* Enabling the clock for GPIOD Peripherals */
	RCC_AHB1ENR |= (1U << 3);

	/* Configure PD13 as general purpose output */
	GPIOD_MODER &= ~(3U << 26);
	GPIOD_MODER |= (1U << 26);

	/* Configure PD12 as general purpose output */
	GPIOD_MODER &= ~(1U << 24);
	GPIOD_MODER |= (1U << 24);

	/* Configure PD13 as push-pull */
	GPIOD_OTYPR &= ~(1U << 13);

	/* Configure PD12 as push-pull */
	GPIOD_OTYPR &= ~(1U << 12);

	/* Configure PD13 as low speed */
	GPIOD_OSPEEDR &= ~(3U << 26);

	/* Configure PD12 as low speed */
	GPIOD_OSPEEDR &= ~(3U << 24);

	/* Configure PD13 as no pull up/down */
	GPIOD_PUPDR &= ~(3U << 26);

	/* Configure PD12 as no pull up/down */
	GPIOD_PUPDR &= ~(3U << 24);

	while(1)
	{
		/*
		 * Automatically SET PD12 and PD13
		 *
		 * BSSR bits 0-15 are SET bits.
		 */
		GPIOD_BSSR = (1U <<13) | (1U <<12);
		delay_ms(500);

		/*
		 * automatically RESET PD12 and PD13
		 *
		 * BSSR bits 16-31 are reset bits.
		 * PD12 -> bit 28
		 * PD13 -> bit 29
		 */
		GPIOD_BSSR = (1U << 29) | (1U <<28);
		delay_ms(500);
	}
}
